[project]
name = "browser-attack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.5.11",
    "garak>=0.12.0",
    "playwright>=1.54.0",
]
